### ISSUE TITLE
Update chai to 4.0.0

### ISSUE THREAD

**Issue by radekmie** [vazco/meteor-universe-e2e#1]
[Release note](https://github.com/chaijs/chai/releases/tag/4.0.0-canary.1)

> Throw when non-existent property is read.
> ```
> expect(true).to.be.ture; // Oops, typo, now Chai will throw an Error
> ```

**Comment by MacRusher** [comment]
I'll not update dependency until chai v4 is considered stable.

Until then you can import own version of chai directly from npm, it should not cause any conflict with dependency bundled with this package.

**Comment by radekmie** [comment]
Just to mention: [chai is already at 4.0.1](http://chaijs.com/releases/).
