### ISSUE TITLE
snapshot testing?

### ISSUE THREAD

**Issue by hanselke** [vazco/meteor-universe-e2e#13]
tried using https://github.com/blogfoster/expect-mocha-snapshot

but am getting      Error: Missing `mochaContext` argument for .toMatchSnapshot().
Did you forget to pass `this` into expect().toMatchSnapshot(this)?

Is there any easy way to include snapshot testing in this package?

 https://medium.com/blogfoster-engineering/how-to-use-the-power-of-jests-snapshot-testing-without-using-jest-eff3239154e5

**Comment by naz** [comment]
Have seen a similar error in a different project and have [created an issue](https://github.com/blogfoster/expect-mocha-snapshot/issues/15) within expect-mocha-snapshot repo.

**Comment by zendranm** [comment]
Hi,

We are not planning on adding snapshot testing to this package. However, it is possible to install and use `expect-mocha-snapshot` alongside the `e2e` package.
